## 3. Special Types of NumPy Arrays

In [19]:
import numpy as np

In [20]:
# Special Types of NumPy Arrays
# NumPy provides special functions to create arrays
# with predefined values such as zeros, ones, a range of numbers,
# and evenly spaced values.
# Important functions:
# 1. np.zeros()       → Creates an array filled with 0s
# 2. np.ones()        → Creates an array filled with 1s
# 3. np.full()        → Creates an array filled with a specified value
# 4. np.arange()      → Creates an array with a sequence of numbers
# 5. np.linspace()    → Creates evenly spaced numbers
# 6. np.eye()         → Creates an identity matrix
# 7. np.empty()       → Creates an uninitialized array

###### Creating an Array of Zeros using np.zeros()

In [21]:
# Array of zeros
arr_zero = np.zeros(5)
print(arr_zero)

[0. 0. 0. 0. 0.]


###### Creating a 2D Array of Zeros

In [22]:
# Creating a 2D array of zeros
arr_zero = np.zeros((2, 3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


###### Creating a 3D Array of Zeros

In [23]:
# Creating a 3D array of zeros
arr_zero = np.zeros((2, 2, 3))
print(arr_zero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


###### Creating an Array of Ones using np.ones()

In [24]:
# Array of Ones
arr_ones = np.ones(5)
print(arr_ones)

[1. 1. 1. 1. 1.]


###### Creating a 3D Array of Ones

In [25]:
# Creating a 3D array of ones
arr_ones = np.ones((2, 2, 5))
print(arr_ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


###### Creating a NumPy Array with Specific Values using np.full()

In [26]:
# Initialize the NumPy array with specific values
arr_spe = np.full(5, 100)
print(arr_spe)

[100 100 100 100 100]


###### Creating a 2D NumPy Array with a Specific Value using np.full()

In [27]:
arr_spe = np.full((2, 5), 100)
print(arr_spe)
# np.full() → Creates an array filled with a specific value.
# (2, 5) → Creates 2 rows and 5 columns.
# 100 → Fills every element with 100.

[[100 100 100 100 100]
 [100 100 100 100 100]]


###### Identity Matrix using np.eye()

In [28]:
# Identity Matrix
# An identity matrix is a square matrix.
# Square matrix → Number of rows = Number of columns.
# Main diagonal values are 1.
# All other values are 0.
identity_matrix = np.eye(4)
print(identity_matrix)
# np.eye(4) → Creates a 4 × 4 identity matrix.
# 4 → Number of rows and columns.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Random package to generate random/synthetic data

In [29]:
# Random Package
# NumPy provides the random module to generate
# random or synthetic data.
# Synthetic Data → Artificially generated data
# that is used for testing, practice, and analysis.
# Important NumPy random functions:
# 1. np.random.rand()      → Random values between 0 and 1
# 2. np.random.random()    → Random values between 0 and 1
# 3. np.random.uniform()   → Random values within a given range
# 4. np.random.normal()    → Random values following a normal distribution
# 5. np.random.choice()    → Randomly selects values from given data
# 6. np.random.seed()      → Makes random results reproducible

###### np.random.rand() – Generate Random Values

In [30]:
# np.random.rand() → Generates random values between 0 and 1.
# 5 → Generates 5 random values.
# Values are greater than or equal to 0 and less than 1.
np.random.rand(5)

array([0.00929626, 0.81274134, 0.19419449, 0.75622526, 0.68916116])

###### np.random.rand(2, 5) – 2D Random Array

In [31]:
# np.random.rand() → Generates random values between 0 and 1.
# (2, 5) → Creates 2 rows and 5 columns.
# Total elements = 2 × 5 = 10.
np.random.rand(2, 5)

array([[0.65750845, 0.1898947 , 0.04909859, 0.99455488, 0.2126753 ],
       [0.97543585, 0.79416691, 0.30867412, 0.69501444, 0.58319374]])

###### np.random.rand(2, 2, 5, 10) – 4D Random Array

In [32]:
# np.random.rand() → Generates random values between 0 and 1.
# (2, 2, 5, 10) → Creates a 4D array.
# 2 → Number of blocks
# 2 → Rows in each block
# 5 → Columns/groups in each row
# 10 → Elements in each group
np.random.rand(2, 2, 5, 10)

array([[[[0.61374446, 0.16767836, 0.30041632, 0.83650497, 0.28966052,
          0.69219528, 0.2002942 , 0.01022149, 0.87650963, 0.59994838],
         [0.57137804, 0.49576086, 0.62089598, 0.47733306, 0.04203133,
          0.17275974, 0.57731643, 0.90244379, 0.84365396, 0.82914039],
         [0.46735739, 0.99086058, 0.01012334, 0.42511273, 0.81176253,
          0.86431103, 0.41255949, 0.82419206, 0.49377003, 0.37245138],
         [0.01121947, 0.81460055, 0.10944038, 0.58854295, 0.29107096,
          0.74138974, 0.46889949, 0.40147   , 0.73805017, 0.6937573 ],
         [0.41801894, 0.63150857, 0.36167235, 0.53517709, 0.23287179,
          0.3611824 , 0.20722403, 0.86740847, 0.79459685, 0.9447233 ]],

        [[0.70437529, 0.8842903 , 0.09672365, 0.87817555, 0.41750573,
          0.14677634, 0.97941766, 0.75720581, 0.86453634, 0.89269394],
         [0.52611635, 0.03536281, 0.46326417, 0.83424349, 0.37829649,
          0.13377945, 0.98829798, 0.97879758, 0.3596348 , 0.12848971],
         [0

###### Uniformly Distributed Random Data

In [33]:
# np.random.uniform() → Generates randomly distributed values
# within a specified range.
# low=1 → Starting value
# high=10 → Upper limit
# size=5 → Generates 5 random values
np.random.uniform(low=1, high=10, size=5)

array([1.05644417, 1.84197871, 3.96789678, 6.07319045, 3.21591949])

##### 2D Random Array

In [34]:
# np.random.uniform() → Generates uniformly distributed random values.
# low=1 → Lower limit
# high=10 → Upper limit
# size=(2,5) → Creates 2 rows and 5 columns.
# Total elements = 2 × 5 = 10
np.random.uniform(low=1, high=10, size=(2,5))

array([[8.04511766, 2.24433975, 2.29266401, 8.72975127, 6.90386447],
       [2.45730889, 9.63451026, 3.30651392, 1.1448982 , 5.49473711]])

###### Normally Distributed Data

In [35]:
# np.random.normal() → Generates random data
# following a normal distribution.
# loc=5 → Mean of the distribution.
# scale=1.2 → Standard deviation (SD).
# size=(2,5) → Creates 2 rows and 5 columns.
# Total elements = 2 × 5 = 10.

np.random.normal(loc=5, scale=1.2, size=(2,5))

array([[5.73784487, 5.46391395, 4.67111473, 6.32463359, 6.40947311],
       [4.69527582, 5.27364707, 6.61323745, 3.14667607, 6.11976223]])

### randon() vs normal()

In [36]:
# np.random.random()
# → Generates random values between 0 and 1.
# → Values are uniformly distributed.
# → Mean and standard deviation are not specified.
# → Used for generating general random values.

# np.random.normal()
# → Generates values following a normal distribution.
# → loc → Mean
# → scale → Standard Deviation
# → Values are usually concentrated around the mean.
# → Used for statistical and synthetic data generation.

###### Categorical Data

In [37]:
# choice() function is used to randomly select values
# from categorical data.
np.random.seed(42)
# seed(42) → Makes the random output reproducible.
np.random.choice(
    ['paradise', 'spirit', 'pushpa', 'bahubali'],
    size=3
)
# size=3 → Selects 3 random values.
# choice() → Randomly selects values from the given categories.

array(['pushpa', 'bahubali', 'paradise'], dtype='<U8')

###### Random Choice with Probability

In [38]:
np.random.choice(
    ['Biryani Boss', 'Fauzi Fighter', 'Spirit Star', 'Pushpa Punch', 'Bahubali King'],
    p=[0.2, 0.05, 0.05, 0.1, 0.6],
    size=10
)

# p → Probability of selecting each category.
# size=10 → Generates 10 random values.
# Higher probability → Higher chance of selection.
# All probabilities together should add up to 1.

array(['Biryani Boss', 'Bahubali King', 'Bahubali King', 'Bahubali King',
       'Biryani Boss', 'Bahubali King', 'Pushpa Punch', 'Biryani Boss',
       'Bahubali King', 'Biryani Boss'], dtype='<U13')