In [3]:
import numpy as np 

###### Sort Operation using np.sort()

In [ ]:
# 1. np.sort() → Sorts the array elements.
# 2. By default, sorting is in ascending order.
# 3. Smallest value → Largest value.
# 4. np.sort() returns a sorted array.
# 5. The original array is not changed.
# 6. It can be used with 1D and multi-dimensional arrays.

In [6]:
# sort operation
 # Sort operation

arr1 = np.array([60, 50, 20, 10, 100, 90])
print(arr1)

[ 60  50  20  10 100  90]


###### Sorting a NumPy Array

In [ ]:
# Purpose: Sorts the elements of arr1 in ascending order.

In [7]:
print(np.sort(arr1))

[ 10  20  50  60  90 100]


###### Reverse Sort using np.sort()

In [ ]:
# Purpose: Sorts the array in descending order, from largest to smallest.

In [9]:
# reverse sort 
print(np.sort(arr1)[::-1])

[100  90  60  50  20  10]


###### Sorting a String Array using np.sort()

In [ ]:
# Purpose: Sorts string values in ASCII order.
# np.sort(arr2) → Sorts the string values.
# Strings are sorted based on their character/ASCII order.
# Capital letters (A-Z) have lower ASCII values than lowercase letters (a-z).
# Therefore, uppercase letters generally come before lowercase letters.
# np.sort() → Ascending order.

In [10]:
# Sorting a string array
# Sorting is done in ASCII format.
# A-Z → 65-90
# a-z → 97-122

arr2 = np.array([
    "Mango Masti",
    "Apple Atta",
    "Banana Boss",
    "Orange Rowdy",
    "Grapes Gang",
    "Watermelon Warrior"
])

print(np.sort(arr2))

['Apple Atta' 'Banana Boss' 'Grapes Gang' 'Mango Masti' 'Orange Rowdy'
 'Watermelon Warrior']


### 8. Concatenation , Stacking , Splitting numpy array,s

###### Concatenating 1D NumPy Arrays

In [ ]:
# Purpose: Combines two or more 1D arrays into one array.
# np.concatenate() → Combines multiple arrays.
# (arr1, arr2, arr3) → Arrays to be combined.
# new_arr → Stores the combined array.
# 1D arrays → Combined into a single 1D array.
# Original arrays are not changed.

In [12]:
# Concatenate the 1D arrays

arr1 = np.array([100, 200, 300])
arr2 = np.array([90, 150, 5])
arr3 = np.array([10, 20, 30])

new_arr = np.concatenate((arr1, arr2, arr3))
print(new_arr)

[100 200 300  90 150   5  10  20  30]


###### Concatenating 2D NumPy Arrays

In [ ]:
# Purpose: Combines two or more 2D arrays into one array.

In [13]:
# concatenate the 2D arrays

arr1 = np.array([
    ["Biryani Boss", "Dosa Don"],
    ["Puri Prince", "Samosa Simba"]
])

arr2 = np.array([
    ["Pizza Pilla", "Pasta Papa"],
    ["Noodles Ninja", "Burger Bujji"]
])

new_arr = np.concatenate((arr1, arr2))
print(new_arr)

[['Biryani Boss' 'Dosa Don']
 ['Puri Prince' 'Samosa Simba']
 ['Pizza Pilla' 'Pasta Papa']
 ['Noodles Ninja' 'Burger Bujji']]


###### Vertical Concatenation of 2D Arrays

In [ ]:
# Purpose: Combines 2D arrays row-wise (vertically) using axis=0.
# axis=0 → Rows are joined vertically.
# Number of columns must be the same.
# Rows are added one below another.
# Original arrays are not changed.

In [18]:
# For concatenation, arrays must have the same dimension.
# We can vertically concatenate 2D arrays of different shapes.
# Vertical concatenation → Row-wise

arr1 = np.array([
    ["Biryani Boss", "Dosa Don"],
    ["Puri Prince", "Samosa Simba"]
])

arr2 = np.array([
    ["Pizza Pilla", "Pasta Papa"],
    ["Noodles Ninja", "Puff Pichha"]
])

new_2d_arr = np.concatenate((arr1, arr2), axis=0)

print(new_2d_arr)

[['Biryani Boss' 'Dosa Don']
 ['Puri Prince' 'Samosa Simba']
 ['Pizza Pilla' 'Pasta Papa']
 ['Noodles Ninja' 'Puff Pichha']]


###### Horizontal Concatenation of 2D Arrays

In [ ]:
# Purpose: Combines 2D arrays column-wise (horizontally) using axis=1
# axis=1 → Columns are joined horizontally.
# Number of rows must be the same.
# Columns are added side by side.
# Original arrays are not changed.

In [19]:
arr1 = np.array([
    ["Samosa Simba", "Puff Pichha"],
    ["Bajji Bujji", "Dosa Don"]
])

arr2 = np.array([
    ["Biryani Boss", "Pasta Papa"],
    ["Noodles Ninja", "Pizza Pilla"]
])

# Horizontal concatenation → Column-wise
new_2d_arr = np.concatenate((arr1, arr2), axis=1)

print(new_2d_arr)

[['Samosa Simba' 'Puff Pichha' 'Biryani Boss' 'Pasta Papa']
 ['Bajji Bujji' 'Dosa Don' 'Noodles Ninja' 'Pizza Pilla']]


###### np.stack() Function

In [20]:
# np.stack function
# Purpose: np.stack() combines arrays by adding a new dimension.
# stack() function will add a "new dimension"
arr1 = np.array(["Chai Champion", "Samosa Simba", "Bajji Bujji"])
arr2 = np.array(["Biryani Boss", "Dosa Don", "PaniPuri Prince"])

stacked_arr = np.stack((arr1, arr2))
print(stacked_arr)

[['Chai Champion' 'Samosa Simba' 'Bajji Bujji']
 ['Biryani Boss' 'Dosa Don' 'PaniPuri Prince']]


#### np.stack() vs np.concatenate()

###### Stacking Arrays Horizontally using axis=1

In [22]:
# Purpose: Both are used to combine NumPy arrays, but they work differently.
# np.concatenate()
# → Joins arrays along an existing dimension.
# → Does NOT add a new dimension.
# → Used to combine rows or columns.

# np.stack()
# → Combines arrays by adding a NEW dimension.
# → Arrays must have the same shape.
# → Used to create a higher-dimensional array.

In [21]:
stacked_arr = np.stack((arr1, arr2), axis=1)

print(stacked_arr)
print(stacked_arr.shape)

[['Chai Champion' 'Biryani Boss']
 ['Samosa Simba' 'Dosa Don']
 ['Bajji Bujji' 'PaniPuri Prince']]
(3, 2)


### vstack() – Vertical Concatenation

#### Same as vertical concatenation

In [24]:
arr1 = np.array([
    ["Drama Red", "Chill Blue"],
    ["Crazy Green", "Royal Purple"]
])

arr2 = np.array([
    ["Sunshine Yellow", "Bubblegum Pink"],
    ["Coffee Brown", "Sky Blue"]
])

vstack_arr = np.vstack((arr1, arr2))

print(vstack_arr)

[['Drama Red' 'Chill Blue']
 ['Crazy Green' 'Royal Purple']
 ['Sunshine Yellow' 'Bubblegum Pink']
 ['Coffee Brown' 'Sky Blue']]


### hstack()

In [25]:
arr1 = np.array([
    ["Dancing Panda", "Lazy Tiger"],
    ["Crazy Monkey", "Sleepy Lion"]
])

arr2 = np.array([
    ["Flying Elephant", "Cool Penguin"],
    ["Funny Rabbit", "Super Cat"]
])

hstack_arr = np.hstack((arr1, arr2))

print(hstack_arr)

[['Dancing Panda' 'Lazy Tiger' 'Flying Elephant' 'Cool Penguin']
 ['Crazy Monkey' 'Sleepy Lion' 'Funny Rabbit' 'Super Cat']]


### splitting numpy array

###### Splitting a NumPy Array using np.split()

In [27]:
# np.split() → Splits an array into multiple equal parts.
# 2 → Number of parts.
# 6 elements ÷ 2 parts = 3 elements in each part.
arr1 = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.split(arr1, 2)
print(split_arr)

[array([10, 20, 30]), array([40, 50, 60])]


###### Accessing an Element from a Split Array

In [28]:
split_arr[0]

array([10, 20, 30])

In [29]:
split_arr[0][2]

np.int64(30)

###### Splitting a 2D Array Column-Wise using np.split()

In [35]:
arr1 = np.array([[10, 20, 40], [30, 40, 100], [50, 60, 35]])
split_arr = np.split(arr1, 3)
print(split_arr)

[array([[10, 20, 40]]), array([[ 30,  40, 100]]), array([[50, 60, 35]])]


In [36]:
split_arr[1]

array([[ 30,  40, 100]])

In [37]:
split_arr[1][0]

array([ 30,  40, 100])

In [38]:
 split_arr[1][0][2]

np.int64(100)