### NumPy – Numerical Python

In [2]:
# NumPy stands for Numerical Python.
# It is a Python library used for numerical and mathematical operations.
# NumPy mainly works with arrays and provides fast operations on numerical data.
# It is commonly used in Data Analytics, Data Science, and Machine Learning.
# Main Point:
# NumPy → Numerical Python → Used for numerical calculations and arrays.
# Definition of NumPy
# NumPy is an open-source Python library used for numerical operations.
# NumPy is mainly implemented using C and C++, with a Python interface.
# It is used for working with arrays and performing mathematical operations.
# Easy Memory:
# NumPy → Numerical Python → Numerical Operations + Arrays

###### Important NumPy Operations

In [3]:
# 1. Installing, Upgrading, Importing NumPy and Checking Version
# 2. Creating NumPy Arrays
# 3. Special Type NumPy Arrays
# 4. Array Shape, Reshape and Transpose
# 5. Size and Data Type of NumPy Array
# 6. Indexing, Slicing and Modification
# 7. Mathematical and Statistical Operations
# 8. Concatenation, Stacking and Splitting NumPy Arrays
# 9. Broadcasting
# 10. Array Comparison and Boolean Operations
# 11. Sorting and Searching Arrays
# 12. Copying and Views
# 13. Random Number Generation
# 14. Handling Missing/NaN Values
# 15. Array Iteration
# 16. Universal Functions (ufuncs)
# 17. Aggregation Functions

## 1. Installing, Upgrading, Importing NumPy and Checking Version

In [4]:
## Installing NumPy
# Run the following command in Anaconda Prompt:
##  conda install numpy
# NumPy already comes with the Anaconda distribution,
# so usually there is no need to install it separately.
# Do not use "pip install numpy" inside an Anaconda environment
# because it can sometimes create package version compatibility issues.
##  After installation, import NumPy:
# import numpy as np
##  Check the installed NumPy version:
# print(np.__version__)
##  Easy Memory:
# Anaconda → NumPy is already included
# Anaconda Prompt → conda install numpy
# Import → import numpy as np
# Version → np.__version__

###### Importing NumPy

In [ ]:
# import numpy → Imports the NumPy library.
# as np → Gives NumPy a short name (alias) called "np".
# np → Used to access NumPy functions and operations.

In [5]:
import numpy as np

###### Checking NumPy Version

In [ ]:
# np → NumPy alias
# __version__ → Returns the installed NumPy version
# Used to check which version of NumPy is installed.

In [6]:
np.__version__

'2.3.5'

## 2. Creating NumPy Arrays

###### Creating a NumPy Array of Integers

In [ ]:
# Main Point:
# NumPy arrays are called ndarray (N-dimensional array).

In [7]:
# Example-1: NumPy array of integers
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


###### Creating a NumPy Array of Float Values

In [ ]:
# type(arr2) → Tells us the object type → ndarray
# arr2.dtype → Tells us the data type of elements → float64

In [8]:
# Example-2: NumPy array of float values
arr2 = np.array([1.2, 2.9, 3.3, 4.9, 5.3])
print(arr2)
print(type(arr2))
print(arr2.dtype)

[1.2 2.9 3.3 4.9 5.3]
<class 'numpy.ndarray'>
float64


###### NumPy Array with Integer and Float Values

In [ ]:
# If integers and floats are present together,
# NumPy converts the integers into floats.
# This is called type promotion.

In [9]:
arr3 = np.array([1.2, 2, 3.3, 4.9, 5])
print(arr3)
print(type(arr3))
print(arr3.dtype)

[1.2 2.  3.3 4.9 5. ]
<class 'numpy.ndarray'>
float64


###### NumPy Array of Strings

In [10]:
# Example-4: NumPy array of strings
arr3 = np.array(["hello", "Class"])
print(arr3)
print(type(arr3))
print(arr3.dtype)
# U → Unicode string data type
# Unicode → Standard used to represent letters, numbers, symbols, and special characters.

['hello' 'Class']
<class 'numpy.ndarray'>
<U5


###### Creating a 2D NumPy Array

In [11]:
arr4 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr4)
print(type(arr4))
print(arr4.dtype)
print(arr4.ndim)    # ndim is used to check the dimension of an array

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
int64
2
