In [3]:
import numpy as np

### Creating Sequences, Shuffling, Permutation and Linearly Separated Data

###### Creating a Sequence using np.arange()

In [4]:
# np.arange() → Used to create a sequence of numbers.
arr1 = np.arange(10)
print(arr1)
# 10 → Stop value (not included).
# Starts from 0 by default.
# Sequence → 0 to 9.

[0 1 2 3 4 5 6 7 8 9]


###### Creating a Sequence with Start and Stop Values

In [5]:
arr1 = np.arange(1, 10)
print(arr1)
# 1 → Starting value (included)
# 10 → Stop value (excluded)
# Generates numbers from 1 to 9.

[1 2 3 4 5 6 7 8 9]


###### Creating a Sequence with Start, Stop and Step

In [6]:
arr1 = np.arange(1, 10, 2)
print(arr1)
# 1 → Starting value (included)
# 10 → Stop value (excluded)
# 2 → Step size
# Generates numbers by increasing 2 each time.

[1 3 5 7 9]


###### Shuffling Elements using np.random.shuffle()

In [7]:
# shuffle() → Randomly changes the order of elements in an array.
arr1 = np.arange(10)
print(arr1)
np.random.shuffle(arr1)
arr1
# np.random.shuffle() → Shuffles the elements randomly.
# It changes the original array.|

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 6, 7, 4, 1, 5, 9, 8, 3])

###### Permutation – Creating a New Shuffled Array

In [8]:
# 1. permutation() returns a new shuffled array.
# 2. It does NOT modify the original array.
# 3. The elements are randomly rearranged.
# 4. Original array can still be used after permutation().
# 5. It is different from shuffle(), which modifies the original array.

In [9]:
# permutation() → Randomly rearranges the elements
# and returns a NEW shuffled array.
arr1 = np.arange(10)
print(arr1)
arr2 = np.random.permutation(arr1)
print(arr2)
print(arr1)
# arr2 → New shuffled array.
# arr1 → Original array remains unchanged.

[0 1 2 3 4 5 6 7 8 9]
[0 2 5 8 3 1 9 4 6 7]
[0 1 2 3 4 5 6 7 8 9]


###### Creating a Linearly Spaced Array using np.linspace()

In [10]:
# linspace() → Creates evenly/linearly spaced values
# between the start and stop values.
arr3 = np.linspace(1, 10, 10)
print(arr3)
# 1 → Starting value (included)
# 10 → Ending value (included)
# 10 → Number of values to generate

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


###### Creating a Linearly Spaced Array using np.linspace()

In [11]:
arr3 = np.linspace(1, 10, 4)
print(arr3)
# 1 → Starting value (included)
# 10 → Ending value (included)
# 4 → Number of values to generate
# Values are evenly spaced between 1 and 10.

[ 1.  4.  7. 10.]


### 4. Array Shape, Reshape and Transpose

In [12]:
# shape     → Gives the size of an array in each dimension.
# reshape() → Changes the shape of an array without changing its data.
# transpose() → Swaps rows and columns of an array.

In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

# 2 → Rows
# 3 → Columns
# Output → (2, 3)

(2, 3)


###### Checking Array Shape using shape

In [14]:
## **Checking the Shape of a NumPy Array**
dresses = np.array([
    ["Biryani Shirt", "Lungi Legend", "Kurta King"],
    ["Saree Queen", "Anarkali Amma", "Half Saree Hero"]
])
print(dresses)
print(dresses.shape)

# shape → Returns the number of rows and columns.
# (2, 3) → 2 rows and 3 columns.

[['Biryani Shirt' 'Lungi Legend' 'Kurta King']
 ['Saree Queen' 'Anarkali Amma' 'Half Saree Hero']]
(2, 3)


###### Reshaping a NumPy Array using reshape()

In [15]:
updated_arr = dresses.reshape(3, 2)
print(updated_arr)
# reshape(3,2) → Changes the array into 3 rows and 2 columns.
# Original shape → (2,3)
# New shape → (3,2)
# Total elements remain the same → 2 × 3 = 3 × 2 = 6

[['Biryani Shirt' 'Lungi Legend']
 ['Kurta King' 'Saree Queen']
 ['Anarkali Amma' 'Half Saree Hero']]


###### Flattening an Array using ravel()

In [16]:
# ravel() → Used to flatten a multi-dimensional array into a 1D array.
arr4 = dresses.ravel()
print(arr4)
# dresses.ravel() → Converts the 2D array into a 1D array.
# It does not change the original array.
# The elements are arranged in row-wise order.

['Biryani Shirt' 'Lungi Legend' 'Kurta King' 'Saree Queen' 'Anarkali Amma'
 'Half Saree Hero']


###### Transpose of a NumPy Array using .T

In [17]:
# transpose → Used to interchange rows and columns.
print(dresses)
print(dresses.T)
# dresses.T → Transposes the array.
# Rows become columns.
# Columns become rows.
# The original array is not changed.

[['Biryani Shirt' 'Lungi Legend' 'Kurta King']
 ['Saree Queen' 'Anarkali Amma' 'Half Saree Hero']]
[['Biryani Shirt' 'Saree Queen']
 ['Lungi Legend' 'Anarkali Amma']
 ['Kurta King' 'Half Saree Hero']]


### 5. Size and Data Type of NumPy Array

In [18]:
# Important Points:
# 1. size → Returns the total number of elements in the array.
# 2. dtype → Returns the data type of the elements.
# 3. size counts all elements, including elements in all dimensions.
# 4. dtype is usually automatically decided by NumPy based on the values.
# 5. Integer values → int64 (commonly)
# 6. Decimal values → float64 (commonly)
# 7. String values → Unicode string type such as <U5
# Easy Memory:
# size → Number of elements
# dtype → Type of elements

###### NumPy Array of Strings – dtype

In [19]:
english = np.array(["one", "two", "three", "four", "five"])

print(english)
print(english.dtype)

# np.array() → Creates a NumPy array.
# english → Stores the string values.
# dtype → Checks the data type of the array elements.
# U → Unicode string type.
# <U5 → Each string can store up to 5 characters.

['one' 'two' 'three' 'four' 'five']
<U5


###### astype() – Data Type Conversion

In [20]:
arr6 = np.array([10.2, 9.2, 9.1, 8.0]).astype(int)
print(arr6)
print(arr6.dtype)
# astype(int) → array datatype ni integer ki convert chestundi.
# Decimal values ni integer values ga convert chestundi.
# Decimal part remove avtundi; rounding jaragadu.
# dtype → converted array ye datatype lo undo chupistundi.

[10  9  9  8]
int64


###### astype() – String to Float Conversion

In [21]:
arr6 = np.array(["10", "20", "30", "40"]).astype(float)

print(arr6)
print(arr6.dtype)

[10. 20. 30. 40.]
float64


###### astype() – Boolean to Integer Conversion

In [31]:
arr6 = np.array([True, False, True, False]).astype(int)
print(arr6)
print(arr6.dtype)

[1 0 1 0]
int64


### 6. Indexing, Slicing and Modification in NumPy

In [32]:
# Indexing → Array lo specific element ni access cheyadaniki use chestam.
# Slicing → Array lo konni elements ni select cheyadaniki use chestam.
# Modification → Array lo unna values ni change cheyadaniki use chestam.
## Indexing    → Oka element ni access cheyadam
## Slicing     → Konni elements ni select cheyadam
## Modification → Element value ni change cheyadam

###### Indexing in a 2D NumPy Array

In [33]:
sweet = np.array([
    ["Gulab Jamun", "Jalebi", "Rasgulla"],
    ["Bobbatlu", "Kajji Kaya", "Mysore Pak"]
])

print(sweet)
print(sweet[1][1])

[['Gulab Jamun' 'Jalebi' 'Rasgulla']
 ['Bobbatlu' 'Kajji Kaya' 'Mysore Pak']]
Kajji Kaya


###### Slicing a 2D NumPy Array

In [35]:
print(sweet[1:2, 1])

['Kajji Kaya']


###### Slicing a 2D NumPy Array

In [36]:
print(sweet[0, 1:3])

['Jalebi' 'Rasgulla']


In [37]:
print(sweet[0, :2])

['Gulab Jamun' 'Jalebi']


###### Slicing All Rows and First Two Columns

In [38]:
print(sweet[:, :2])

[['Gulab Jamun' 'Jalebi']
 ['Bobbatlu' 'Kajji Kaya']]


###### Negative Indexing in a 2D NumPy Array

In [39]:
print(sweet[-1, -2])

Kajji Kaya


###### Negative Slicing in a 2D NumPy Array

In [40]:
print(sweet[-1:, -1:-2:-1])

[['Mysore Pak']]
